name: CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - '*.ignore'
      - LICENSE
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: builder
        run: docker build -t atpoint/test:xxx .
